# https://cloud.google.com/run/docs/deploying?hl=en#sidecars
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/launch-stage: BETA
  name: web
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen1 #or gen2
    spec:
      containers:
        - image: asia-northeast1-docker.pkg.dev/cloudrun-envoy-sample/web/hono-app:latest
          ports:
            - containerPort: 8080
        - image: SIDECAR_IMAGE
